# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f9e9cf768db6881167e6e2d3794df98734416de04e5b1cc10225cf10b098fe1e9f924704390eeb951f0f1f347c0cb105c90298893a9f61e98854ae76c2b0d04

test:
  secret_key_base: 3c5cd7941216ed6fb4e969fa417e3991bd6868e0ff67717a2d283d770fc059a81bb61c5c39b8f0b76af15240045268687a2155d456dbeff8033b7366da1badd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
